/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe; also reports the active LLM mode (mock|gemini).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/pitch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Pitch */
        post: operations["generate_pitch_api_customers__customer_id__pitch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pitches/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Pitches Bulk */
        post: operations["generate_pitches_bulk_api_pitches_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pitches/bulk/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bulk Status */
        get: operations["get_bulk_status_api_pitches_bulk__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pitches/bulk/{batch_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Bulk Status */
        get: operations["stream_bulk_status_api_pitches_bulk__batch_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkBatchCreated */
        BulkBatchCreated: {
            /** Batch Id */
            batch_id: number;
            /** Total */
            total: number;
        };
        /** BulkBatchStatus */
        BulkBatchStatus: {
            /** Batch Id */
            batch_id: number;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
            /** Running */
            running: number;
            /** Pending */
            pending: number;
            /** Complete */
            complete: boolean;
            /** Live */
            live: boolean;
            /** Items */
            items: components["schemas"]["BulkItemStatus"][];
        };
        /** BulkItemStatus */
        BulkItemStatus: {
            /** Customer Id */
            customer_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
            /** Pitch Id */
            pitch_id?: number | null;
            /** Error */
            error?: string | null;
        };
        /** BulkPitchRequest */
        BulkPitchRequest: {
            /** Customer Ids */
            customer_ids: string[];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * CustomerDetail
         * @description Full detail: customer info + usage history + offer ladder + latest pitch.
         */
        CustomerDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Region */
            region: string;
            current_plan: components["schemas"]["PlanRef"];
            /** Monthly Price */
            monthly_price: number;
            /** Tenure Months */
            tenure_months: number;
            /**
             * Contract End Date
             * Format: date
             */
            contract_end_date: string;
            /** Usage Archetype */
            usage_archetype: string;
            /** Avg Monthly Gb */
            avg_monthly_gb: number;
            /** Last Month Gb */
            last_month_gb: number;
            /** Usage History */
            usage_history: components["schemas"]["UsagePoint"][];
            offer_ladder: components["schemas"]["OfferLadder"];
            latest_pitch?: components["schemas"]["PitchRead"] | null;
        };
        /**
         * CustomerSummary
         * @description Row shape for the customer list.
         */
        CustomerSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            current_plan: components["schemas"]["PlanRef"];
            /** Tenure Months */
            tenure_months: number;
            /** Avg Monthly Gb */
            avg_monthly_gb: number;
            /**
             * Contract End Date
             * Format: date
             */
            contract_end_date: string;
            /** Latest Pitch Status */
            latest_pitch_status?: string | null;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Expiring This Month */
            expiring_this_month: number;
            /** By Tier */
            by_tier: components["schemas"]["TierCount"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Llm Mode */
            llm_mode: string;
        };
        /** OfferLadder */
        OfferLadder: {
            /** Rungs */
            rungs: components["schemas"]["OfferRung"][];
            /**
             * Recommended
             * @enum {string}
             */
            recommended: "retain" | "value_upgrade" | "upsell";
        };
        /** OfferRung */
        OfferRung: {
            /**
             * Type
             * @enum {string}
             */
            type: "retain" | "value_upgrade" | "upsell";
            target_plan: components["schemas"]["PlanRef"];
            /** Monthly Price */
            monthly_price: number;
            /** Term Months */
            term_months: number;
            /** Vs Current Delta */
            vs_current_delta: number;
            /** Headline */
            headline: string;
        };
        /** Page[CustomerSummary] */
        Page_CustomerSummary_: {
            /** Data */
            data: components["schemas"]["CustomerSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PitchGenerateRequest */
        PitchGenerateRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** PitchRead */
        PitchRead: {
            status: components["schemas"]["PitchStatus"];
            /** Text */
            text?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Grounding Ok
             * @default false
             */
            grounding_ok: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * PitchStatus
         * @enum {string}
         */
        PitchStatus: "not_generated" | "generating" | "ready" | "failed";
        /** PlanRef */
        PlanRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Speed Mbps */
            speed_mbps: number;
            /** Price Myr */
            price_myr: number;
        };
        /** TierCount */
        TierCount: {
            plan: components["schemas"]["PlanRef"];
            /** Count */
            count: number;
        };
        /** UsagePoint */
        UsagePoint: {
            /** Month */
            month: string;
            /** Gb */
            gb: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: {
                /** @description matches name or customer id */
                search?: string | null;
                /** @description filter by plan id */
                plan?: string | null;
                sort?: "tenure" | "avg_gb" | "contract_end_date";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
                /** @description only contracts ending this calendar month */
                expiring?: boolean;
                /** @description min tenure in months */
                tenure_min?: number | null;
                /** @description max tenure in months */
                tenure_max?: number | null;
                /** @description min avg monthly usage (GB) */
                usage_min?: number | null;
                /** @description max avg monthly usage (GB) */
                usage_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CustomerSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    generate_pitch_api_customers__customer_id__pitch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PitchGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_pitches_bulk_api_pitches_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkPitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkBatchCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bulk_status_api_pitches_bulk__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkBatchStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_bulk_status_api_pitches_bulk__batch_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
